### ISSUE TITLE
UI error if widget is inside Expanded

### ISSUE THREAD

**Issue by mishatron** [huextrat/menu_button#7] opened 2020-05-15 14:30 UTC
I want MenuButton to expand the available width. But if I put it in Expanded - it is broken down

**Comment by lucas-sesti** [comment] 2020-05-15 14:34
I have the same problem but, i resolved my problem using media query and calculate the correctly width, i don't know if this resolve your problem..

**Comment by mishatron** [comment] 2020-05-15 14:37
this is the last variant, becuase I have not only this widget in the row. Should be fixed

**Comment by huextrat** [comment] 2020-05-15 14:40
Yes I had that problem too, I'll have some time to watch next week. Can you put a code to reproduce the problem so the resolution will be more efficient. Thanks

**Comment by dipcse07** [comment] 2020-06-16 13:45
@huextrat have you also updated for this one too??

**Comment by huextrat** [comment] 2020-06-16 13:48
@dipcse07 No i'm working on it this afternoon to find a suitable solution. Can you confirm the the issue is on the `child` & `toggledChild` property ?

**Comment by dipcse07** [comment] 2020-06-16 13:51
yes on the drop down menu items or the child items . wait a second i will add two screen shot..

**Comment by dipcse07** [comment] 2020-06-16 13:57
When there is only 2 button items then there is another two button area in the drop down menu items before even selecting the button items..i guess.. 
![Screen Shot 2020-06-16 at 7 54 26 PM](https://user-images.githubusercontent.com/19185636/84783712-570fbf00-b00b-11ea-8871-cc2b6546d2e2.png)

When there is 4 button items then after selecting one button item it shows the remaining 3 button item with extra another area for button item
![Screen Shot 2020-06-16 at 7 52 22 PM](https://user-images.githubusercontent.com/19185636/84783930-8aeae480-b00b-11ea-8837-ebaa17de4a2b.png)

these are the problems i am having..

**Comment by huextrat** [comment] 2020-06-16 14:11
Okay that sounds like another problem that I think is solved in the latest master version. Can you confirm by retrieving master?

**Comment by dipcse07** [comment] 2020-06-16 14:15
okay..  i am upgrading..

**Comment by huextrat** [comment] 2020-06-16 14:16
@dipcse07 v1.2.0+1 should solve your problem

**Comment by huextrat** [comment] 2020-06-16 14:25
@dipcse07 Ok and you are using an Expanded widget or not ?

**Comment by dipcse07** [comment] 2020-06-16 14:27
if i have understood currectly i am not for menu button...  i have only used which is given in the how to use section of the pub.dev for this packages..

here is the code: 

`  body: Container(
          alignment: Alignment.center,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
//              FlatButton(
//                onPressed: () {
//                  getData();
//
//                  print('the count: $count');
//                },
//                child: Text('get data'),
//              ),



              MenuButton(
                child: SizedBox(
                  width: 83,
                  height: 40,
                  child: Padding(
                    padding: const EdgeInsets.only(left: 16, right: 11),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                        Flexible(

                          child: Text(
                            selectedItem,
                            style: TextStyle(color: Colors.black),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                        SizedBox(
                            width: 12,
                            height: 17,
                            child: FittedBox(
                                fit: BoxFit.fill,
                                child: Icon(
                                  Icons.arrow_drop_down,
                                  color: Colors.grey,
                                )
                            )`

**Comment by huextrat** [comment] 2020-06-16 15:06
@mishatron @lucas-sesti `menu_button: 1.2.1` should solve the issue when you have MenuButton in Expanded widget. I'm gonna close the issue please tell me if you still have the problem.

@dipcse07 Your problem looks like it's not related to this issue, please open a new one with code sample and same screenshot as above ;) Thanks

**Closed by huextrat** 2020-06-16 15:06 UTC
Labels: bug

**Comment by dipcse07** [comment] 2020-06-16 15:08
okay i will do that now..
